"""
Synthetic Crop & Pathology Reference Classifier.

============================== HONESTY NOTICE ==============================
The classifier trained here learns from `core/data/simulated_crop_pathology_
reference.csv` -- a FABRICATED, ILLUSTRATIVE dataset generated by this
project (see `core/data/generate_reference.py`... conceptually; the
generation script is documented in this module's docstring, not shipped
separately). It is NOT real crop or disease photography, and its 10 "crop"
and 15 "class" categories are generic placeholders (Crop01..Crop10,
Class01..Class15) with fabricated feature signatures -- they do not
correspond to validated real-world crop or disease identities.

A first attempt used a dataset provided by the user, but that file's
labels were verified to be statistically independent of its own feature
columns (cross-validated accuracy at chance level) -- training on it would
have produced a classifier indistinguishable from random guessing while
LOOKING like a working model. Rather than ship that, this module uses a
dataset deliberately constructed to have learnable structure, purely to
demonstrate the classification/training machinery working correctly.

This exists to demonstrate HOW a trained classifier could work in this
pipeline once real, validated, labelled photographs are available -- not
to provide real crop identification or disease diagnosis. Every prediction
this module returns is labelled "SIMULATED DEMO" and must not be used for
real agronomic decisions.
=============================================================================
"""
from __future__ import annotations

import os

import numpy as np

from .indices import _gray, ndvi, ndwi
from .texture_features import glcm_features

CSV_PATH = os.path.join(os.path.dirname(__file__), "data", "simulated_crop_pathology_reference.csv")

FEATURE_COLUMNS = [
    "glcm_contrast", "glcm_homogeneity", "entropy", "hue_mean", "saturation_mean",
    "value_mean", "edge_density", "vegetation_index", "texture_energy",
    "shape_factor", "moisture_proxy",
]

_crop_model = None
_class_model = None
_train_report = None
_load_error = None


def _rgb_to_hsv_opencv_scale(image_array: np.ndarray) -> tuple[float, float, float]:
    """Real HSV means, rescaled to the OpenCV-style convention (H:0-179, S/V:0-255)
    used by the reference dataset's schema."""
    from skimage.color import rgb2hsv
    hsv = rgb2hsv(image_array / 255.0)
    h_mean = float(hsv[:, :, 0].mean()) * 179.0
    s_mean = float(hsv[:, :, 1].mean()) * 255.0
    v_mean = float(hsv[:, :, 2].mean()) * 255.0
    return h_mean, s_mean, v_mean


def _real_shape_factor(image_array: np.ndarray) -> float:
    """Real canopy-region solidity (0-1) as a shape-factor proxy."""
    from skimage import filters, morphology, measure
    r = image_array[:, :, 0].astype(float)
    g = image_array[:, :, 1].astype(float)
    b = image_array[:, :, 2].astype(float)
    total = r + g + b + 1e-6
    exg = 2 * (g / total) - (r / total) - (b / total)
    try:
        mask = morphology.remove_small_objects(exg > filters.threshold_otsu(exg), min_size=50)
        labeled = measure.label(mask)
        props = measure.regionprops(labeled)
        if not props:
            return 0.5
        largest = max(props, key=lambda p: p.area)
        return float(largest.solidity)
    except Exception:
        return 0.5


def extract_reference_schema_features(image_array: np.ndarray) -> dict:
    """
    Compute REAL, genuinely-measured features from an actual image, in the
    same schema as the (simulated) reference dataset's columns, so a model
    trained on that schema can run inference on real photos.
    """
    gray = _gray(image_array)
    hist, _ = np.histogram(gray, bins=256, range=(0, 255), density=True)
    hist = hist[hist > 0]
    entropy = float(-np.sum(hist * np.log2(hist)))

    glcm = glcm_features(image_array)
    h_mean, s_mean, v_mean = _rgb_to_hsv_opencv_scale(image_array)
    veg = ndvi(image_array)
    moisture = (ndwi(image_array).mean() + 1.0) / 2.0  # rescale -1..1 to 0..1

    edges = filters_sobel_mean(gray)

    return {
        "glcm_contrast": glcm["contrast"],
        "glcm_homogeneity": glcm["homogeneity"],
        "entropy": entropy,
        "hue_mean": h_mean,
        "saturation_mean": s_mean,
        "value_mean": v_mean,
        "edge_density": edges,
        "vegetation_index": float(veg.mean()),
        "texture_energy": glcm["energy"],
        "shape_factor": _real_shape_factor(image_array),
        "moisture_proxy": float(np.clip(moisture, 0, 1)),
    }


def filters_sobel_mean(gray: np.ndarray) -> float:
    from skimage import filters
    return float(filters.sobel(gray / 255.0).mean())


def _ensure_trained() -> None:
    global _crop_model, _class_model, _train_report, _load_error
    if _crop_model is not None or _load_error is not None:
        return
    try:
        import pandas as pd
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.model_selection import cross_val_score

        df = pd.read_csv(CSV_PATH)
        X = df[FEATURE_COLUMNS].values
        y_crop = df["crop"].values
        y_class = df["class"].values

        _crop_model = RandomForestClassifier(n_estimators=150, random_state=0, n_jobs=-1).fit(X, y_crop)
        _class_model = RandomForestClassifier(n_estimators=150, random_state=0, n_jobs=-1).fit(X, y_class)

        crop_cv = cross_val_score(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1),
                                   X, y_crop, cv=3).mean()
        class_cv = cross_val_score(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1),
                                    X, y_class, cv=3).mean()
        _train_report = {
            "n_rows": len(df), "n_crops": df["crop"].nunique(), "n_classes": df["class"].nunique(),
            "crop_cv_accuracy": float(crop_cv), "class_cv_accuracy": float(class_cv),
        }
    except Exception as e:
        _load_error = str(e)


def predict(image_array: np.ndarray) -> dict:
    """
    Run the SIMULATED-DEMO reference classifier on one image's real,
    extracted features. Always returns a prominent disclaimer alongside
    the prediction.
    """
    _ensure_trained()
    if _load_error is not None:
        return {"available": False, "note": f"Reference classifier unavailable: {_load_error}"}

    feats = extract_reference_schema_features(image_array)
    x = np.array([[feats[c] for c in FEATURE_COLUMNS]])

    crop_probs = dict(zip(_crop_model.classes_, _crop_model.predict_proba(x)[0]))
    class_probs = dict(zip(_class_model.classes_, _class_model.predict_proba(x)[0]))

    return {
        "available": True,
        "features_used": feats,
        "crop_probabilities": crop_probs,
        "class_probabilities": class_probs,
        "train_report": _train_report,
        "disclaimer": (
            "SIMULATED DEMONSTRATION ONLY. This classifier is trained on a fabricated, "
            "illustrative dataset (core/data/simulated_crop_pathology_reference.csv), not real "
            "crop or disease photography. 'Crop01'..'Crop10' and 'Class01'..'Class15' are generic "
            "placeholder categories, not validated real-world identities. Do not use these "
            "predictions for real agronomic decisions. To get a real classifier, add genuinely "
            "labelled photos via the Group/Crop Label field in Field & Sensor Data -- the app's "
            "separate real k-NN classifier will train on YOUR real, labelled data."
        ),
    }
